#!/usr/bin/env python

import sys

from motor_widget.motor_widget_module import MotorWidget
from rqt_gui.main import Main

plugin = 'motor_widget'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
