from pysm import StateMachine, State, Event

carousel = StateMachine("carousel")
drill = StateMachine("drill")
melt = StateMachine("melt")
filtration = StateMachine("filtration")
cat = StateMachine("cat")

initializing = State("initializing")
manual = State("manual")
rotating = State("rotating")
drilling = State("drilling")
melting = State("melting")
carousel.add_state(initializing, initial=True)
carousel.add_state(manual)
carousel.add_state(rotating)
carousel.add_state(drilling)
carousel.add_state(melting)

drill_idle = State("drill_idle")
drill_drilling = State("drill_drilling")
drill_retracting = State("drill_retracting")
drill_stopped = State("drill_stopped")
drill.add_state(drill_idle, initial=True)
drill.add_state(drill_drilling)
drill.add_state(drill_retracting)
drill.add_state(drill_stopped)


melt_idle = State("met_idle")
melt_descending = State("melt_descending")
melt_rockwell = State("melt_rockwell")
melt_bowl = State("melt_bowl")
melt_retracting = State("retracting")
melt_stopped = State("stopped")
melt.add_state(melt_idle, initial=True)
melt.add_state(melt_descending, initial=True)
melt.add_state(melt_rockwell, initial=True)
melt.add_state(melt_bowl, initial=True)
melt.add_state(melt_retracting, initial=True)
melt.add_state(melt_stopped, initial=True)

filtration_idle = State("filtration_idle")
filtration_filter = State("filtration_filter")
filtration_bypass = State("filtration_bypass")
filtration_backwash = State("filtration_backwash")
filtration.add_state(filtration_idle, initial=True)
filtration.add_state(filtration_filter)
filtration.add_state(filtration_bypass)
filtration.add_state(filtration_backwash)

cat_idle = State("cat_idle")
cat_descending = State("cat_descending")
cat_retracting = State("cat_retracting")
cat_scan = State("cat_scan")
cat_stopped = State("cat_stopped")
cat.add_state(cat_idle, initial=True)
cat.add_state(cat_descending)
cat.add_state(cat_retracting)
cat.add_state(cat_scan)

if __name__ == '__main__':
